- name: Apply security patches
  hosts: servers
  become: yes

  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Reboot the server if needed
      reboot:
        msg: "Rebooting the server after applying updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: ansible_distribution == 'Ubuntu'
